services:
- type: web
  name: ai-expenses-api
  env: node
  plan: free
  buildCommand: npm install
  startCommand: node src/index.js
  autoDeploy: true
  envVars:
  - key: NODE_VERSION
    value: 20
  - key: PORT
    value: 10000
  - key: MONGO_URI
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: GEMINI_API_KEY
    sync: false
